### ISSUE TITLE
[BUG]Issue with account login using pychatgpt library

### ISSUE THREAD

**Issue by sherlockHlb** [rawandahmad698/PyChatGPT#102]
Subject: Issue with account login using pychatgpt library

**Describe the bug**

When I try to login to my account using the `pychatgpt` library, I get an error message saying that the API key provided is incorrect.

**To Reproduce**

1. Install the `pychatgpt` library using `pip install pychatgpt`
2. Use the following code to try to log in to my account:

from pychatgpt import Chat, Options

options = Options()
options.logs = True
options.track = True

chat = Chat(email="[*@gmail.com](*)", password="*", options=options)

3. Run the code and see the error message: "Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com."

**Expected behavior**

I expect to be able to successfully log in to my account using the `pychatgpt` library.

**Screenshots**

I do not have any screenshots to share.

**Version Info**

- Chatgptpy version: 1.2.0
- Dependency version: Not applicable

**Additional context**

I have checked my account and confirmed that my username and password are correct. I have also checked the link provided in the error message to see if there is anything I need to do to obtain a valid API key, but I have not been able to find anything relevant. I would appreciate any help or guidance you can provide to help me resolve this issue.

**Comment by rawandahmad698** [comment]
`pychatgpt` is not the name of the package. Use: `pip3 install chatgptpy --upgrade`

**Comment by sherlockHlb** [comment]
This is the output I received:

Requirement already satisfied: chatgptpy in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (1.0.6)
Requirement already satisfied: tls-client in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chatgptpy) (0.1.5)
Requirement already satisfied: requests in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chatgptpy) (2.28.1)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chatgptpy) (0.4.6)
Requirement already satisfied: svglib in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chatgptpy) (1.4.1)
Requirement already satisfied: bs4 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chatgptpy) (0.0.1)
Requirement already satisfied: reportlab in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chatgptpy) (3.6.12)
Requirement already satisfied: beautifulsoup4 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from bs4->chatgptpy) (4.11.1)
Requirement already satisfied: pillow>=9.0.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from reportlab->chatgptpy) (9.3.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->chatgptpy) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->chatgptpy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->chatgptpy) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->chatgptpy) (2022.12.7)
Requirement already satisfied: lxml in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from svglib->chatgptpy) (4.9.0)
Requirement already satisfied: tinycss2>=0.6.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from svglib->chatgptpy) (1.2.1)
Requirement already satisfied: cssselect2>=0.2.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from svglib->chatgptpy) (0.7.0)
Requirement already satisfied: webencodings in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from cssselect2>=0.2.0->svglib->chatgptpy) (0.5.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4->bs4->chatgptpy) (2.3.2.post1)

**Comment by sherlockHlb** [comment]
But the problem is still unresolved
