### ISSUE TITLE
[Feature Request] Add a toggle to use proxy or not in the `ask` API.

### ISSUE THREAD

**Issue by ParadoxZW** [rawandahmad698/PyChatGPT#105]
It seems that only the procedure of 'login in and get access token' needs proxy in China, while the `ask` API doesn't.

Since using proxy servers may cause unstability, I'd prefer use proxy when updating access tokens, not use when calling `ask`.

**Comment by rawandahmad698** [comment]
```python
        answer, previous_convo, convo_id = ChatHandler.ask(auth_token=access_token,
                                                           prompt=prompt,
                                                           conversation_id=self.conversation_id,
                                                           previous_convo_id=self.previous_convo_id,
                                                           proxies=self.options.proxies)
```
`options.proxies` are used, so make sure to add an option, and add proxies, it's used for all requests

**Comment by ParadoxZW** [comment]
So if I initial a `ChatHandler` with proxy set in the `options`, but call `ask` without passing the argument of `proxies`, will it use proxy or not, when making the post requests to talk with ChatGPT?
