### ISSUE TITLE
[BUG] Package works very slowly

### ISSUE THREAD

**Issue by lobanovkos** [rawandahmad698/PyChatGPT#109]
**Describe the bug**
This package works very slowly, even request "Hello" takes about 3 minutes to proceed. If I try the same with pyChatGPT, it gives me answer in 10 sec

**To Reproduce**
1. Try PyChatGPT 
2. Try the same request with pyChatGPT
3. See the difference

**Expected behavior**
To have this package working more or less the same speed as another one

**Comment by Pengchengistaken** [comment]
same, really needs to improve the timing.

**Comment by rawandahmad698** [comment]
Thanks guys. Watchout for another version which will greatly improve this

**Comment by lobanovkos** [comment]
@rawandahmad698 Cool! Do you know when?

**Comment by rawandahmad698** [comment]
Updated in 1.0.8, Check it out on Readme.md
