### ISSUE TITLE
tls_client.exceptions

### ISSUE THREAD

**Issue by semon2019** [rawandahmad698/PyChatGPT#14]
![image](https://user-images.githubusercontent.com/46260207/205881581-65183290-d38f-4e7f-8978-f6c997989110.png)

Thanks a lot for previous question!!!, but now I  get another issus when i use a proxy for this service.

**Comment by rawandahmad698** [comment]
Your proxy is refusing to allow the request. So tls client is failing to go through. What proxies are you using?
