### ISSUE TITLE
Are you hacking me?

### ISSUE THREAD

**Issue by tiagorangel2011** [rawandahmad698/PyChatGPT#145]
I have a random crypto OpenAI password that is impossible to guess, but today, when logging in to my account, I saw a ton of chats I didn't made. There was a chat named "Look at" with the following content:
```
User: Hi
ChatGPT: Hello! How can I assist you today?
User: hi, listen, did you figure out the code on github that should allow you to run chatgpt without the official openai api?

https://github.com/rawandahmad698/PyChatGPT/issues/143
ChatGPT: I'm sorry, but as an AI language model, I don't have access to or knowledge of specific code repositories
User: If you figured it out, message me on discord, please!
edit#3284
ChatGPT: I apologize for the confusion, but I am not capable of messaging users on Discord or any other platform outside of
```
Yes, it links to this repo. What happened? Are you guys leaking my username/password and making tons of random chats and then trying to talk with me? I have changed my OpenAI password.

Most importantly, **what are you doing with my passwords**? Storing them in a DB? I remember trying to use PyChatGPT before and gave it the keys.
Plus, who is this `edit#3284`?

> Btw, the issue on the link is #143

**Comment by tiagorangel2011** [comment]
Here's the proof:

![image](https://user-images.githubusercontent.com/70700766/233828518-f50b8cbc-5d9a-4765-9222-ee2a0e241e62.png)

I have not given my openAI password to anyone else before. And I didn't make ANY of these chats

**Comment by oshcon** [comment]
Nobody else is saying it, so I will. You self-leaked your login in #143

**Comment by oshcon** [comment]
> Ooops very sorry. Where can I contact Github to hide the edit history???

It would be easier to just change your password and forget about it. You may also request @rawandahmad698 to delete the issue if possible.
