### ISSUE TITLE
Can you publish it to pypi?

### ISSUE THREAD

**Issue by fuergaosi233** [rawandahmad698/PyChatGPT#16]
Thanks for your great work. I am trying to use this SDK in my project, but it seems that it can only be installed through Git clone, so have you considered the publish it to pypi?

**Comment by rawandahmad698** [comment]
Yes. It's in the "What's Next" section. (Goal is 300 stars) 💯💯

**Comment by acheong08** [comment]
@rawandahmad698 +1

**Comment by rawandahmad698** [comment]
@fuergaosi233 @casey @alx @acheong08 Out now!!
