### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by foreveryuu** [rawandahmad698/PyChatGPT#18]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/119954620/205951258-bb4cf4e4-073e-4a5e-b8c9-539f6845a13c.png">

why show this error: IndexError: list index out of range

**Comment by foreveryuu** [comment]
Thank you for your reply

During I try to use proxy, I also show this error: https://github.com/rawandahmad698/PyChatGPT/issues/14

I am using VPN by Clash, what proxy should I fill in?

**Comment by foreveryuu** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/119954620/205958384-1f3e7d2a-9eb1-4e35-80e3-f8b5d422cfed.png">

shows this error

**Comment by rawandahmad698** [comment]
Okay, please include the steps to reproduce this including proxies. If they're confidential. Email me at rawa@rawa.dev
