### ISSUE TITLE
Unable to enter captcha code 

### ISSUE THREAD

**Issue by kissinger31** [rawandahmad698/PyChatGPT#22]
ScreenShot link
https://ibb.co/bBjh00x

**Comment by rawandahmad698** [comment]
Make a fake account. And try that again. I'll add support for 2fa later

**Comment by rawandahmad698** [comment]
Fixed, check out the new content

**Comment by smartnikocj** [comment]
> got the captcha.png and entered it, still, [OpenAI][6] Email not found, Check your email address and try again!
> 
> I did have that email address and I can login with the password with 2fa off, I'm using python3.10, not working still. works OK with interface.
> 
> do I need sign out of the web login at openai?

got the same problem, ''[OpenAI][6] Email not found, Check your email address and try again!''
double check email is correct.
and check the source code, should be not get the 302.
