### ISSUE TITLE
Conversation Resume

### ISSUE THREAD

**Issue by josiahzimm** [rawandahmad698/PyChatGPT#25]
Is there any way to resume a conversation so the context it had from before is still active if I need to restart the script?

**Comment by rawandahmad698** [comment]
That's a good idea. Will look into it

**Comment by NithSelv** [comment]
Hey, I'm new to open source and I was wondering if I could make a PR for this?

**Comment by rawandahmad698** [comment]
Hi. Welcome.. you can. Why not?

**Comment by rawandahmad698** [comment]
Added in v1.0.4
