### ISSUE TITLE
Incorrect API Key Provided: Bearer

### ISSUE THREAD

**Issue by seangilleran** [rawandahmad698/PyChatGPT#26]
Testing with `cli_chat()` I get the following result:
```
>> Access token is valid.
>> Starting CLI chat session...
You: Hello!
Chat GPT is typing... |#----|Error: {"detail":{"message":"Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}
>> Failed to get a response from the API.
```
Login seems to go smoothly otherwise. OpenAI does provide an account-level API key but I'm assuming that it's not necessary here (?)

**Comment by acheong08** [comment]
> Login seems to go smoothly otherwise. OpenAI does provide an account-level API key but I'm assuming that it's not necessary here (?)

Seems like the token isn't being added to the header properly. OpenAI just updated their API a few hours ago to *attempt* to block bots. I have been able to bypass that by modifying some header fields, namely more cookies being added.

**Comment by rawandahmad698** [comment]
> > Login seems to go smoothly otherwise. OpenAI does provide an account-level API key but I'm assuming that it's not necessary here (?)
> 
> Seems like the token isn't being added to the header properly. OpenAI just updated their API a few hours ago to _attempt_ to block bots. I have been able to bypass that by modifying some header fields, namely more cookies being added.

Headers are fine, there's nothing special about the headers that would require much attention, I was asleep at the time but I found out that special characters, such as some emojis/unicode have this behavior on the API.

**Comment by yueyunyu** [comment]
![image](https://user-images.githubusercontent.com/42567175/207859986-5f2dfb74-03c3-4acc-a79d-b45a539712ac.png)

Just waiting？
