### ISSUE TITLE
Step 8 error

### ISSUE THREAD

**Issue by whklhh** [rawandahmad698/PyChatGPT#30]
"[OpenAI][8] While most of the process was successful, "
"Auth0 didn't issue an access token, Use proxies or retry."

Then I print the response.text, got:
```html
<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/auth/error","query":{},"buildId":"xxx","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script>
```

**Comment by rawandahmad698** [comment]
Retry the request. This happens sometimes and it works on the next request

**Comment by whklhh** [comment]
I have tried 3 times but all got errors.
I suddenly realized that this server is in HK, maybe this is the reason.
Thank you for answer.

**Comment by rawandahmad698** [comment]
Welcome. You can use proxies if it's censored in your country
