### ISSUE TITLE
I'm using a clash VPN but there is an error

### ISSUE THREAD

**Issue by semon2019** [rawandahmad698/PyChatGPT#32]
![image](https://user-images.githubusercontent.com/46260207/206151003-5c18af66-9f9b-451f-8b7e-db838e3319c8.png)

And this is my clash VPN:
![image](https://user-images.githubusercontent.com/46260207/206151214-79a0f2cd-7f24-4829-814b-360e69d6a27a.png)

when i fill in this proxy, and the error as follows:
![image](https://user-images.githubusercontent.com/46260207/206152818-be9a00a4-a52c-4337-98d3-239fc50ebae4.png)

**Comment by rawandahmad698** [comment]
This is a proxy error. Checkout https://webproxies.io
