### ISSUE TITLE
    raise Exceptions.Auth0Exception("[OpenAI][8] While most of the process was successful, " pychatgpt.classes.exceptions.Auth0Exception: [OpenAI][8] While most of the process was successful, Auth0 didn't issue an access token, Use proxies or retry.

### ISSUE THREAD

**Issue by Rockyzsu** [rawandahmad698/PyChatGPT#33]
After input captcha, it gives error:

    raise Exceptions.Auth0Exception("[OpenAI][8] While most of the process was successful, "
pychatgpt.classes.exceptions.Auth0Exception: [OpenAI][8] While most of the process was successful, Auth0 didn't issue an access token, Use proxies or retry.

**Comment by rawandahmad698** [comment]
It gives you the error message, this is not an issue with the lib
