### ISSUE TITLE
Add a function to obtain the sentence ChatGPT is thinking about

### ISSUE THREAD

**Issue by 2659170494** [rawandahmad698/PyChatGPT#36]
Although Python cannot perform other operations when using the Ask function to make ChatGpt think, I can separate a thread for PyChatGpt. Can I try to access the thread where PyChatGpt is located in another thread and get the sentences that ChatGpt is generating

**Comment by rawandahmad698** [comment]
You mean, as its being typed? since the response method is a data steam

**Comment by rawandahmad698** [comment]
good idea. will look into it

**Comment by NithSelv** [comment]
I was also thinking about tackling this issue along with the other PR. Will make 2 separate PRs.

**Comment by 2659170494** [comment]
@NithSelv @rawandahmad698 
As long as it is easy to understand and merge, it is certainly good.

The main reason is that there is no document in the warehouse at present, so I can't understand what functions are contained in the library.

Even the sample code of Readme.md has not been updated in time:

access_ token, expiry = OpenAI.Auth. get_ access_ token() -> access_ token, expiry = OpenAI.get_ access_ token()
is_ expired = OpenAI.Auth. token_ expired() # Returns True or False -> is_ expired = OpenAI. token_ expired() # Returns True or False

If the proxies in the Chat function are in the form of string（“ http://localhost:8080 "), you will encounter an SSL error. It can only be in the form of a dictionary ({'https':' http://127.0.0.1:1145 ',"http":' http://127.0.0.1:1145 '}) Use proxies

If you want to understand the library, you can only refer to the code of the library file, which is not something you can learn in a short time
I hope relevant documents will appear later

**Comment by NithSelv** [comment]
Just wanted to clarify if this is what is required or if I have a misunderstanding of the issue. Essentially we have two threads and we want to be able to get the sentences generated by ChatGPT from the other thread. 

So in the following scenario:

The thread running ChatGPT has a list of prompts to ask and for each prompt, as soon as we get a response, we can queue the (prompt, result).

The thread that relies on the results can just check the queue for new input.

The queue is global and thread-safe so there shouldn't be any race conditions.

**Comment by 2659170494** [comment]
> Just wanted to clarify if this is what is required or if I have a misunderstanding of the issue. Essentially we have two threads and we want to be able to get the sentences generated by ChatGPT from the other thread.
> 
> So in the following scenario:
> 
> The thread running ChatGPT has a list of prompts to ask and for each prompt, as soon as we get a response, we can queue the (prompt, result).
> 
> The thread that relies on the results can just check the queue for new results.
> 
> The queue is global and thread-safe so there shouldn't be any race conditions.
> 
> I was thinking of having a variable for the queue passed in the Ask function (default is None) and if it is not None, then the prompt and responses would get stored there to be read from another thread.

Well, I also saw the commits you submitted in the questions mentioned

If it passes, I may try to make a document to explain these functions

**Comment by rawandahmad698** [comment]
Fixed by @NithSelv
