### ISSUE TITLE
[OpenAI][4] IndexError: list index out of range

### ISSUE THREAD

**Issue by cced3000** [rawandahmad698/PyChatGPT#38]
openai.py", line 211, in _part_four
state = re.findall(r"state=(.*)", response.text)[0]
IndexError: list index out of range

I've tried many times retry the request 。

I have tried to use proxy or not,  the same error.

**Comment by rawandahmad698** [comment]
You may be rate limited by Auth0. Could you try using a different account?

**Comment by acheong08** [comment]
@rawandahmad698 It seems to be a common error. There are a lot of people experiencing this on my side as well, myself included

**Comment by acheong08** [comment]
The response is blank

**Comment by rawandahmad698** [comment]
Interesting. I will go over the process.

**Comment by acheong08** [comment]
It seems to be an issue on their side. The response code is correct but nothing is returned. I think their service is temporarily down (auth)

**Comment by MirrorCY** [comment]
After changing accounts and proxy and waiting a while, can sometimes goto Phase 8.
```
openai.py", line 359, in _part_eight
    raise Exceptions.Auth0Exception("[OpenAI][8] While most of the process was successful, "
pychatgpt.classes.exceptions.Auth0Exception: [OpenAI][8] While most of the process was successful, Auth0 didn't issue an access token, Use proxies or retry.
```

**Comment by acheong08** [comment]
Valid auth tokens are also not getting a response. They are down

**Comment by acheong08** [comment]
```
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0m66QYwAAAACPkK4lk1D/TKtD2BBYPextU0pDRURHRTA1MTUAZTY2YjhiMDMtMDc5My00NDA5LTk3NzMtMmU2MTJlNzFhMWUz</span></div></div></body></html>
```

**Comment by rawandahmad698** [comment]
Confirmed, I'm having this issue too

**Comment by olyble** [comment]
yes,i have

**Comment by cesarhuret** [comment]
Getting the same error too

**Comment by 2659170494** [comment]
Fortunately, I have encountered this problem.

But I tried it again and it worked again. Perhaps this is a probabilistic problem?

**Comment by 2659170494** [comment]
After I tried again, it failed again

I tried to log in on the website, but then I found that I could not log in and I was stuck in the link: https://chat.openai.com/auth/login?callbackUrl=https%3A%2F%2Fchat.openai.com%2F&error=OAuthSignin



This may be a problem with the server

**Comment by rawandahmad698** [comment]
### Update

looks like this is an issue with their servers, I constantly get 5xx errors. Sometimes I can't even login using a browser.

**Comment by acheong08** [comment]
It has been fixed up to part seven. AccessToken authentication already back up

**Comment by acheong08** [comment]
It's back up again. Very unreliable

**Comment by rawandahmad698** [comment]
That's Azure for you, So much for the "best IaaS" out there. This would have never happened if they chose AWS lol

**Comment by 2659170494** [comment]
😂😂😂

**Comment by rawandahmad698** [comment]
@acheong08 happens only if you're inexperienced, with all due respect. I manage two AWS accounts and I never had billing issue 

To outline, I'm 2X certified, and currently a Community Builder for AWS

**Comment by acheong08** [comment]
True. I am still a student/intern and have no experience

**Comment by rawandahmad698** [comment]
Update 2: 

As per https://discord.gg/openai -- the servers are currently **down**

**Comment by rawandahmad698** [comment]
Update 2: 

Looks like everything is back on, Including token regeneration.
```
[OpenAI][9] Saving access token...
[OpenAI][8] Saved access token
Hello there! It's nice to meet you. Is there something on your mind that you would like to talk about? I'm here to help answer any questions you might have.

```
