### ISSUE TITLE
Sorry, just one stupid question

### ISSUE THREAD

**Issue by lhlxx2010** [rawandahmad698/PyChatGPT#39]
ERROR: Could not find a version that satisfies the requirement chatgptpy (from versions: none)
ERROR: No matching distribution found for chatgptpy

**Comment by HiHatDoDot** [comment]
Check your python version

**Comment by 2659170494** [comment]
You may want to check whether your PyPi software source has this library. And whether your Python version is compatible with this library

**Comment by pranavchat14** [comment]
Faced same issue. chatgptpy requires Python 3.9 or higher. 
Create a fresh conda environment with `conda create -n chatgpt python=3.9`, activate it with `conda activate chatgpt` and install with `pip install chatgptpy --upgrade`.
