### ISSUE TITLE
if there could support the way by api-key to login?

### ISSUE THREAD

**Issue by ticoAg** [rawandahmad698/PyChatGPT#40]
openai support the api-key, it's also a way to auth. so there will be no need to generate cookies, find the pwd, no google account problem that can't login with email.thanks for your contribution

**Comment by 2659170494** [comment]
If I guess correctly, ChatGpt and DALL · E are not the same thing.

DALL · E is based on GPT-3, while ChatGPT is based on GPT-3.5(https://mbd.baidu.com/newspage/data/landingsuper?context={%22nid%22:%22news_9297968712323586824%22}&n_type=-1&p_from=-1 ). At present, the documents and introductions on the official website are also applicable to DALL · E and Codex. But there is no mention of ChatGPT

In addition, ChatGPT has no information about open source or open API, which will also be replied in ChatGPT.

In addition, the ApiKey you are talking about will be charged in some cases.

**Comment by ticoAg** [comment]
yeah
i just tried the way to use davinci-003 by api_key but find no example for chatgpt
If your speculation is true, we can only express regret and look forward to the arrival of new hope
thanks
