### ISSUE TITLE
【suggest】proxies support socks5 

### ISSUE THREAD

**Issue by skefy** [rawandahmad698/PyChatGPT#47]
```
Using proxies: socks5://192.168.2.1:1080
>> Error when calling OpenAI API: Missing dependencies for SOCKS support.
>> Failed to get a response from the API.
```

**Comment by skefy** [comment]
Using proxies: socks5://192.168.2.1:1080
>> Error when calling OpenAI API: Missing dependencies for SOCKS support.
>> Failed to get a response from the API.

**Comment by MirrorCY** [comment]
Try run `pip install pysocks`

**Comment by skefy** [comment]
> Try run `pip install pysocks`

It works
