### ISSUE TITLE
Can't pass previous_convo_id to Chat

### ISSUE THREAD

**Issue by Mazawrath** [rawandahmad698/PyChatGPT#49]
I would like to be able to decide whether the context of the previous messages are kept, so when I run `chat.ask()` I would like to be able to pass the variable found on line 22, `previous_convo_id`.
However, when I try to pass it along with the prompt I get the error `discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: ask() got an unexpected keyword argument 'previous_convo_id'`.
Is this variable somehow private? Pardon my lack of experience with Python but I'm not sure why I would have access to `prompt` but not any of  the other variables.

**Comment by Mazawrath** [comment]
I see the reason now. When importing `Chat` it's getting imported from `src/pychatgpt/main.py`.
So I guess this is more of a feature request to let us set our own variable to `previous_convo_id` so you can decide whether OpenAI should use the context of a previous thread.

**Comment by rawandahmad698** [comment]
Interesting. Will push a new version shortly 🙏

**Comment by rawandahmad698** [comment]
Fixed

**Comment by Mazawrath** [comment]
https://github.com/rawandahmad698/PyChatGPT/blob/3b8041719e5aab3ed73604c4048b8f4cd3a5317a/src/pychatgpt/main.py#L159
Is there is a way to pass it here? What I was thinking is that you can choose on the fly which conversation ID to refer to, rather then giving it an ID only once when you login into OpenAI.

**Comment by rawandahmad698** [comment]
That's a good idea. Thank you. 

Will make sure its implemented.

**Comment by Mazawrath** [comment]
Out of curiosity, what is the difference between `conversation_id` and `previous_convo_id`? If these values don't match will it still use the `previous_convo_id`'s context?
