### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yinzhangyue** [rawandahmad698/PyChatGPT#5]
auth.py", line 357, in part_eight
```    
access_token = re.findall(r"accessToken\":\"(.*)\"", next_data.text)[0]
```
IndexError: list index out of range

**Comment by cretaceous-creature** [comment]
mark, the same.
Besides, if proxy is added, following error occurs
`[OpenAI] Password: xia*******
[OpenAI] Using proxy: http://127.0.0.1:1080
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    open_ai_auth.begin()
  File "/home/chen/Desktop/PyChatGPT/Classes/auth.py", line 109, in begin
    self.session.proxies(proxies)
TypeError: 'dict' object is not callable
`

**Comment by rawandahmad698** [comment]
Hi, Please try again using a proxy, this is because of rate limiting, We use https://webshare.io proxies and I just tested the code again, everything words ok

**Comment by rawandahmad698** [comment]
> mark, the same.
> Besides, if proxy is added, following error occurs
> `[OpenAI] Password: xia******* [OpenAI] Using proxy: http://127.0.0.1:1080 Traceback (most recent call last): File "main.py", line 43, in <module> open_ai_auth.begin() File "/home/chen/Desktop/PyChatGPT/Classes/auth.py", line 109, in begin self.session.proxies(proxies) TypeError: 'dict' object is not callable`

Okay, thank you for this, This should've been `self.session.proxies = proxies` it's now fixed

**Comment by cretaceous-creature** [comment]
> > mark, the same.
> > Besides, if proxy is added, following error occurs
> > `[OpenAI] Password: xia******* [OpenAI] Using proxy: http://127.0.0.1:1080 Traceback (most recent call last): File "main.py", line 43, in <module> open_ai_auth.begin() File "/home/chen/Desktop/PyChatGPT/Classes/auth.py", line 109, in begin self.session.proxies(proxies) TypeError: 'dict' object is not callable`
> 
> Okay, thank you for this, This should've been `self.session.proxies = proxies` it's now fixed

Thank you, for me the same proxy it worked after the new commit, but not now.
`[OpenAI] Using proxy: http://127.0.0.1:1080
[OpenAI] Beginning auth process
[OpenAI][1] Making request to https://chat.openai.com/auth/login
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    open_ai_auth.begin()
  File "/home/chen/Desktop/PyChatGPT/Classes/auth.py", line 124, in begin
    response = self.session.get(url=url, headers=headers)
  File "/home/chen/.local/lib/python3.8/site-packages/tls_client/sessions.py", line 343, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/home/chen/.local/lib/python3.8/site-packages/tls_client/sessions.py", line 326, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://chat.openai.com/auth/login": unexpected EOF`

**Comment by rawandahmad698** [comment]
Retry the request.

**Comment by cretaceous-creature** [comment]
> Retry the request.

Thanks, I figure out that I am using an trojan proxy, which is socks not http lol.
