### ISSUE TITLE
Return result is incomplete

### ISSUE THREAD

**Issue by Lxk-Kallen** [rawandahmad698/PyChatGPT#52]
It seems like only a fraction of the results are returned, Below is my problem and the result I got

ask:
请帮我写一个前端页面，要求：列表、分页、创建、删除、修改，再美化一下页面

answer:
以下是一个基于JavaScript框架（如Angular、React、Vue）开发的简单前端页面，它提供了列表、分页、创建、删除、修改等功能：

```
<!DOCTYPE html>
<html>
<head>
  <title>TMS系统</title>
  <style>
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #f2f2f2;
    }
    button {
      padding: 10px 20px;
      background-color: #4CAF50;
      color: white;
      border: none;
      cursor: pointer;
    }
    .pagination {
      display: inline-block;
    }
    .pagination a {
      color: black;
      float: left;
      padding: 8px 16px;
      text-decoration: none;
    }
    .pagination a.active {
      background-color: #4CAF50;
      color: white;
    }
    .pagination a:hover:not(.active) {
      background-color: #ddd;
    }

**Comment by rawandahmad698** [comment]
I don't know what language that is. But since it involves Angular/HTML, I assume you asked for some code?

**Comment by Lxk-Kallen** [comment]
Below is my full code

```
from pychatgpt import Chat
from typing import Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()
chat = Chat(email="email", password="passw") 

@app.get("/ask")
async def get(ask): 
    answer = chat.ask(ask);
    print('ask:' + ask + 'answer:' + answer);
    return answer;

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=port)
```

**Comment by FuryMartin** [comment]
> I don't know what language that is. But since it involves Angular/HTML, I assume you asked for some code?

He means the code is truncated.

**Comment by Lxk-Kallen** [comment]
> > I don't know what language that is. But since it involves Angular/HTML, I assume you asked for some code?
> 
> He means the code is truncated.

Yes

**Comment by Lxk-Kallen** [comment]
![image](https://user-images.githubusercontent.com/72729568/206405018-bacfc645-89f8-47b8-bb0d-426dd5563b24.png)
Not just the code, what I think is truncated is the reply

**Comment by happy-game** [comment]
> I don't know what language that is. But since it involves Angular/HTML, I assume you asked for some code?

He was asking why chatGPT gave him an incomplete reply, because in his screenshot chatGPT stopped after only half of the sentence. But I think it's a problem with chatGPT that when its reply is too long, it will truncates the reply into pieces and doesn't make sure the sentence is complete when it's truncated. In this case, just say "continue(in chinese is"继续")" to chatGPT to get the rest of the reply.
