### ISSUE TITLE
Not running on Raspberry Pi?

### ISSUE THREAD

**Issue by gijski** [rawandahmad698/PyChatGPT#53]
I try to install on my raspberry pi, and get this error:

ERROR: Could not find a version that satisfies the requirement chatgptpy (from versions: none)
ERROR: No matching distribution found for chatgptpy

Tried manually by downloading the code and running it from Thonny Python IDE, but then I get errors too.

Not possible to run on raspberry pi?

**Comment by rawandahmad698** [comment]
PyChatGPT requires python >= 3.9

**Comment by gijski** [comment]
Thanks for the feedback. Now updating, expect it will work then. Thanks!
