### ISSUE TITLE
Bug: ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Avangardum** [rawandahmad698/PyChatGPT#61]
When I try to run the app I get the following:
C:\Users\Yuriy\Downloads\PyChatGPT-master\src\pychatgpt>python main.py
Traceback (most recent call last):
  File "C:\Users\Yuriy\Downloads\PyChatGPT-master\src\pychatgpt\main.py", line 10, in <module>
    from .classes import openai as OpenAI
ImportError: attempted relative import with no known parent package

**Comment by rawandahmad698** [comment]
What's your pychatgpt version?

Also post your code

**Comment by Avangardum** [comment]
I used the last version (for 9.12.2022). I didn't edit any code, just downloaded the program and ran main.py. Am I not supposed to do that?

**Comment by NataN431** [comment]
i have the same problem :c

**Comment by ZEGEIZI** [comment]
i have encountered the same issue.

**Comment by rawandahmad698** [comment]
Will fix asap.

**Comment by ZEGEIZI** [comment]
i am using python3.10

**Comment by dfi69** [comment]
@rawandahmad698 Got the update but it didnt seem to fix the issue. Python 3.10.

**Comment by dfi69** [comment]
Python 3.10 on MacOS (ARM)

**Comment by rawandahmad698** [comment]
> `Traceback (most recent call last):
> 
>   File "/Users/beady/Github/ChatGPT/PyChatGPT/src/pychatgpt/main.py", line 10, in <module>
> 
>     from .classes import openai as OpenAI
> 
> ImportError: attempted relative import with no known parent package`
> 
> 
> 
> git log: commit 83b00a0bb81bb6a0cce8c3ad8e2c8c4aa14efcd7
> 
> Author: Rawand Ahmed Shaswar <rawandahmad698@gmail.com>
> 
> Date:   Thu Dec 8 15:54:24 2022 +0300
> 
> 
> 
>     Version 1.0.3

That's v1.0.3 still

**Comment by rawandahmad698** [comment]
Update using 
`pip3 install chatgptpy --upgrade`

**Comment by dfi69** [comment]
beady@beadyf878  ~/Github/ChatGPT/PyChatGPT/src/pychatgpt   master ⍟1   pip3 install chatgptpy --upgrade                                                                                                                 ✔  1538  22:11:37
Requirement already satisfied: chatgptpy in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (1.0.4)
Collecting chatgptpy
  Downloading chatgptpy-1.0.5-py3-none-any.whl (14 kB)
Requirement already satisfied: tls-client in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from chatgptpy) (0.1.5)
Requirement already satisfied: colorama in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from chatgptpy) (0.4.6)
Requirement already satisfied: reportlab in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from chatgptpy) (3.6.12)
Requirement already satisfied: requests in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from chatgptpy) (2.27.1)
Requirement already satisfied: svglib in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from chatgptpy) (1.4.1)
Requirement already satisfied: bs4 in /Users/beady/.local/lib/python3.10/site-packages (from chatgptpy) (0.0.1)
Requirement already satisfied: beautifulsoup4 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from bs4->chatgptpy) (4.11.1)
Requirement already satisfied: pillow>=9.0.0 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from reportlab->chatgptpy) (9.3.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from requests->chatgptpy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from requests->chatgptpy) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from requests->chatgptpy) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from requests->chatgptpy) (1.26.9)
Requirement already satisfied: lxml in /Users/beady/.local/lib/python3.10/site-packages (from svglib->chatgptpy) (4.9.1)
Requirement already satisfied: tinycss2>=0.6.0 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from svglib->chatgptpy) (1.2.1)
Requirement already satisfied: cssselect2>=0.2.0 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from svglib->chatgptpy) (0.7.0)
Requirement already satisfied: webencodings in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from cssselect2>=0.2.0->svglib->chatgptpy) (0.5.1)
Requirement already satisfied: soupsieve>1.2 in /Users/beady/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from beautifulsoup4->bs4->chatgptpy) (2.3.2)
Installing collected packages: chatgptpy
  Attempting uninstall: chatgptpy
    Found existing installation: chatgptpy 1.0.4
    Uninstalling chatgptpy-1.0.4:
      Successfully uninstalled chatgptpy-1.0.4
Successfully installed chatgptpy-1.0.5
 beady@beadyf878  ~/Github/ChatGPT/PyChatGPT/src/pychatgpt   master ⍟1  python main.py                                                                                                                                    ✔  1539  22:11:40
Traceback (most recent call last):
  File "/Users/beady/Github/ChatGPT/PyChatGPT/src/pychatgpt/main.py", line 10, in <module>
    from .classes import openai as OpenAI
ImportError: attempted relative import with no known parent package

**Comment by NataN431** [comment]
I still have the issue, I dowloaded the changes and the pip3 install chatgptpy --upgrade

**Comment by rawandahmad698** [comment]
I can't reproduce your issue. Post your code including steps to reproduce please

**Comment by NataN431** [comment]
\PyChatGPT-master\src\pychatgpt\main.py", line 11, in <module>
    from .classes import openai as OpenAI
ImportError: attempted relative import with no known parent package

 I dowloaded the code, I put in the cmd: pip install chatgptpy --upgrade, then python main.py and there this error came out. I don't change anything of the code. Anyway, I never run a single python program so I probably miss a step or something?

latest version of the code
python 3.10
windows
