### ISSUE TITLE
ModuleNotFoundError: No module named 'pychatgpt'

### ISSUE THREAD

**Issue by SwpuEsine** [rawandahmad698/PyChatGPT#63]
ModuleNotFoundError: No module named 'pychatgpt'

**Comment by SwpuEsine** [comment]
but i have installed  the module，and run show this in pycharm

**Comment by LiviaChowdary** [comment]
hey how'd you even get this to run. I'm so confused right now it keeps saying the directory does not exist.

**Comment by LiviaChowdary** [comment]
I did try that but nothing happened at all. I tried adding the token code after collecting my api token but that didnt work either and im not sure why it seems to download all the libraries and then it just is blank
