### ISSUE TITLE
OpenAI's _part_four is no longer working

### ISSUE THREAD

**Issue by programmerguys** [rawandahmad698/PyChatGPT#65]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/114569860/206598479-38812e77-16ab-4213-a072-0558e1aaa8e5.png">
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/114569860/206598668-0cbe1e8d-dc3a-4a8f-bccd-276c56fccd64.png">

**Comment by programmerguys** [comment]
the response.text is ‘’

**Comment by marvelg** [comment]
Same issue here!

**Comment by semon2019** [comment]
same issue

**Comment by programmerguys** [comment]
Sometimes after getting the state, the following error occurs in part8.
![image](https://user-images.githubusercontent.com/114569860/206610784-dbf7a301-ac81-4aa8-9877-4b779a92a0ca.png)

**Comment by rawandahmad698** [comment]
No worries. Will look into it, It's 5am here 😭

**Comment by marvelg** [comment]
@rawandahmad698 You are the true MVP. Thank you so much. This has been really2 helpful!

**Comment by programmerguys** [comment]
> No worries. Will look into it, It's 5am here 😭 [不用擔心。會研究它，在這裡是凌晨5點😭] x

Thanks for your hard work, I'm at 11:00 noon and I need your help badly

**Comment by pen-ho** [comment]
same issue
