### ISSUE TITLE
I use email and password to log in, but it raises an exception: You have been rate limited.

### ISSUE THREAD

**Issue by qiuhuachuan** [rawandahmad698/PyChatGPT#72]
I use email and password to log in, but it raises an exception: You have been rate limited.

My code is as follows:

`from revChatGPT.revChatGPT import Chatbot

config = {
    "email": "{my_email_name}@gmail.com",
    "password": "{my_password}"
}

chatbot = Chatbot(config, conversation_id=None)

response = chatbot.get_chat_response("Hello world")
chatbot.reset_chat()
print(response)`

**Comment by rawandahmad698** [comment]
Move to https://github.com/rawandahmad698/PyChatGPT/issues/71
