### ISSUE TITLE
i/o timeout, set proxies failed

### ISSUE THREAD

**Issue by CreamColored** [rawandahmad698/PyChatGPT#75]
I hava tried but it failed.
![image](https://user-images.githubusercontent.com/38077102/206650253-fe184c4d-855b-451f-87d0-9028e78583b7.png)
![image](https://user-images.githubusercontent.com/38077102/206650855-2d740367-d935-4aba-863f-bd8704d3fdac.png)
Could you please give me an example?

**Comment by gd1m3y** [comment]
their api is down :-)

**Comment by rawandahmad698** [comment]
This is an issue with their API, as @gd1m3y stated, We have no timeouts in place
