### ISSUE TITLE
ModuleNotFoundError: No module named 'pychatgpt'

### ISSUE THREAD

**Issue by joytianya** [rawandahmad698/PyChatGPT#76]
ModuleNotFoundError: No module named 'pychatgpt'
pip install pychatgpt
after the installation was successful, this error appeared. Could you please tell me how to fix it?

**Comment by ShellMonster** [comment]
pip3 install chatgptpy --upgrade

**Comment by reycn** [comment]
You need to make sure that your working Python has the module installed.

**Comment by joytianya** [comment]
> pip3 install chatgptpy --upgrade

thank you very much, you are right
