### ISSUE TITLE
Segmentation fault on MacOS

### ISSUE THREAD

**Issue by ParadoxZW** [rawandahmad698/PyChatGPT#79]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/32508168/206728429-4a6f4523-a98b-41f0-bb56-466612dda79f.png">

**Comment by rawandahmad698** [comment]
Please include your platform, dependency version, and steps to reproduce this issue

**Comment by horsto** [comment]
same here

**Comment by ParadoxZW** [comment]
## platform
MacBook Air (Retina, 13-inch, 2020), 1.1 GHz 4core Intel Core i5
OS: macOS Catalina, v10.15.7 (19H2)

## python version
as you can see in the screenshot

## pip list
```
Package            Version
------------------ -----------
beautifulsoup4     4.11.1
bs4                0.0.1
certifi            2022.9.24
charset-normalizer 2.1.1
chatgptpy          1.0.5
colorama           0.4.6
cssselect2         0.7.0
idna               3.4
lxml               4.9.1
Pillow             9.3.0
pip                22.2.2
reportlab          3.6.12
requests           2.28.1
setuptools         65.5.0
soupsieve          2.3.2.post1
svglib             1.4.1
tinycss2           1.2.1
tls-client         0.1.5
urllib3            1.26.13
webencodings       0.5.1
wheel              0.37.1
```

## reproduce
just import the package.

**Comment by cicilzx** [comment]
I have the same problem.
