### ISSUE TITLE
[OpenAI][8][CRITICAL] Access Token: Not found Auth0 did not issue an access token.

### ISSUE THREAD

**Issue by 1054429861** [rawandahmad698/PyChatGPT#82]
![微信截图_20221209232919](https://user-images.githubusercontent.com/53285787/206736794-945af069-35dd-434f-800c-cfb2fab602e9.png)
![微信截图_20221209232905](https://user-images.githubusercontent.com/53285787/206736809-307db239-7d03-49cd-9ea2-f1835c10cb38.png)

after log [OpenAI][8] All good ,next log tips Access Token: Not found Auth0 did not issue an access token.
I'm sure that I can connect the ChatGPT

I debug find it
![image](https://user-images.githubusercontent.com/53285787/206737948-132c54ca-75bc-4580-a9bf-f330b7325363.png)

**Comment by rawandahmad698** [comment]
Discussion in https://github.com/rawandahmad698/PyChatGPT/issues/71
