### ISSUE TITLE
Is there a way to toggle off terminal logs?

### ISSUE THREAD

**Issue by shobrook** [rawandahmad698/PyChatGPT#83]
Hi,

I'd like to incorporate this into my app but whenever I ask ChatGPT a question, connection logs are printed to the terminal, and there appears to be no way to toggle these off. There should be a flag (e.g. `verbose=False`) added to the `Options` object to suppress all terminal output.

Thanks!

**Comment by rawandahmad698** [comment]
In the next version. I'll be adding this. Thank you 🙏

**Comment by rawandahmad698** [comment]
Added in v1.0.6, checkout readme.me
