### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by JazBern** [rawandahmad698/PyChatGPT#84]
Why am I getting this error?
/python3.9/site-packages/tls_client/sessions.py", line 326, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://chat.openai.com/auth/login": dial tcp [::1]:8080: connect: connection refused

**Comment by rawandahmad698** [comment]
Proxy error. Retry with a better proxy

**Comment by yueyunyu** [comment]
> Why am I getting this error? /python3.9/site-packages/tls_client/sessions.py", line 326, in execute_request raise TLSClientExeption(response_object["body"]) tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://chat.openai.com/auth/login": dial tcp [::1]:8080: connect: connection refused



> Why am I getting this error? /python3.9/site-packages/tls_client/sessions.py", line 326, in execute_request raise TLSClientExeption(response_object["body"]) tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://chat.openai.com/auth/login": dial tcp [::1]:8080: connect: connection refused

Have you solved it? Me too

**Comment by yueyunyu** [comment]
![image](https://user-images.githubusercontent.com/42567175/207860400-33d05e99-5859-4550-9a5a-a29b27471d8f.png)

Just waiting??

**Comment by Thaison03** [comment]
I have the same problem. Is there any solution?

**Comment by Thaison03** [comment]
> Proxy error. Retry with a better proxy

I have the same problem. Is there any solution?
