### ISSUE TITLE
Your authentication token has expired. Please try signing in again.

### ISSUE THREAD

**Issue by zexinxu0604** [rawandahmad698/PyChatGPT#85]
How can I signing in again? Why did this happen?

**Comment by zexinxu0604** [comment]
the full error message
[Status Code] 401 | [Response Text] {"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}}

**Comment by rawandahmad698** [comment]
Thank you. Will look into it.

**Comment by zexinxu0604** [comment]
I just tried to start a chat again and it worked normally.
