### ISSUE TITLE
I want to be able to specify conversation_id and previous_convo_id in chat.ask()

### ISSUE THREAD

**Issue by waxsd100** [rawandahmad698/PyChatGPT#87]
After passing `conversation_id` and `previous_convo_id` to `chat.ask()`,
it would be great if ChatHandler.ask() could return the values of `conversation_id` and `previous_convo_id` in the response,
or if they could be obtained from somewhere else.

---

You can take over a conversation with just chat.ask() like this.
https://github.com/TUSB/DiscordChatGPT/commit/d9313484d7f9b7ab3c6c74d6b08315bdcc83f4af

The above implementation is a destructive change and a bad implementation from a code standpoint.
This is for reference only...

**Comment by waxsd100** [comment]
He said something similar over here.
https://github.com/rawandahmad698/PyChatGPT/issues/49#issuecomment-1342896833

**Comment by rawandahmad698** [comment]
https://github.com/rawandahmad698/PyChatGPT/pull/73 Soon
