### ISSUE TITLE
from .classes import openai as OpenAI ImportError: attempted relative import with no known

### ISSUE THREAD

**Issue by aiai97** [rawandahmad698/PyChatGPT#91]
I just cloned the repo and run the command "pip install -r requirements.txt" and I tried to run "python main.py" in the directory named pychatgpt.Unluckily,it failed.I tried the method mentioned in https://www.datasciencelearner.com/importerror-attempted-relative-import-parent-package/ and it didn't help.Plus，my environment is to rename pip to pip3 and I need to rename python as python3.I don't know whether the issue is caused by this.

**Comment by rawandahmad698** [comment]
Why would you clean the repo? You should install via PyPi.
