### ISSUE TITLE
[BUG]TypeError: __init__() got an unexpected keyword argument 'email'

### ISSUE THREAD

**Issue by fzp0424** [rawandahmad698/PyChatGPT#95]
**Describe the bug**
When I manually set the token, it reported "TypeError: __init__() got an unexpected keyword argument 'email'"

**Version Info (please complete the following information):**
- Chatgptpy version 1.0.6
- Dependency version python 3.9

**Additional context**
TypeError                                 Traceback (most recent call last)
Cell In [5], line 5
      2 from pychatgpt import OpenAI
      4 # Manually set the token
----> 5 OpenAI.Auth(email="my email", password="my password").save_access_token(access_token="here is my token", expiry=time.time() + 3600)
      7 # Get the token, expiry
      8 access_token, expiry = OpenAI.get_access_token()

TypeError: __init__() got an unexpected keyword argument 'email'

**Comment by rawandahmad698** [comment]
typo, please use `OpenAI.Auth(email_address="my email", password="my password").save_access_token(access_token="here is my token", expiry=time.time() + 3600)
`
