### ISSUE TITLE
[BUG] The package name conflict

### ISSUE THREAD

**Issue by Yan-Zero** [rawandahmad698/PyChatGPT#97]
**Describe the bug**
The package conflicts with [pyChatGPT](https://github.com/terry3041/pyChatGPT) because they both use the same name, "pychatgpt", and Windows systems do not distinguish between upper and lower case.

**Expected behavior**
The package should use a different name to avoid conflicts with pyChatGPT.

**Screenshots**
N/A

**Version Info (please complete the following information):**
- Chatgptpy version: 1.0.6
- Dependency versions:
  - tls-client: 0.1.5
  - requests: 2.28.1
  - colorama: 0.4.6
  - svglib: 1.4.1
  - bs4: 0.0.1
  - reportlab: 3.6.12
  - beautifulsoup4: 4.11.1
  - pillow: 9.3.0
  - charset-normalizer: 2.1.1
  - idna: 3.4
  - urllib3: 1.26.13
  - certifi: 2022.12.7
  - lxml: 4.9.0
  - tinycss2: 1.2.1
  - cssselect2: 0.7.0
  - webencodings: 0.5.1
  - soupsieve: 2.3.2.post1

**Additional context**
N/A

**Comment by Yan-Zero** [comment]
It would be more appropriate for the package's name, "chatgptpy," to also be the name of the folder it is contained in, rather than using all lowercase "pychatgpt."

**Comment by rawandahmad698** [comment]
The guy took my name before I got the package published, this repo was source code only at the beginning.

**Comment by Yan-Zero** [comment]
I apologize for installing the pyChatGPT package earlier. I did so because the [ChineseAiDungeonChatGPT](https://github.com/bupticybee/ChineseAiDungeonChatGPT) depended on it. I have now replaced the pyChatGPT with your package.
